config/routes.rb
Rails.application.routes.draw do
  resources :locals do
    resources :products
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/local.rb
class Local < ApplicationRecord
  attr_accessor :name, :detail, :photo, :price
  validates :name,  :presence => true
  validates :detail, :presence => true
  validates :photo, :presence => true
  validates :price, :presence => true
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]

  # GET /locals
  # GET /locals.json
  def index
    @locals = Local.all
  end

  # GET /locals/1
  # GET /locals/1.json
  def show
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1
  # PATCH/PUT /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locals_url, notice: 'Local was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit(:name, :razonsocial, :rut)
    end
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/views/locals/_form.html.erb
<%= form_with(model: local, local: true) do |form| %>
  <% if local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :razonsocial %>
    <%= form.text_field :razonsocial %>
  </div>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locals/edit.html.erb
<h1>Editing Local</h1>

<%= render 'form', local: @local %>

<%= link_to 'Show', @local %> |
<%= link_to 'Back', locals_path %>

app/views/locals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Razonsocial</th>
      <th>Rut</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locals.each do |local| %>
      <tr>
        <td><%= local.name %></td>
        <td><%= local.razonsocial %></td>
        <td><%= local.rut %></td>
        <td><%= link_to 'Show', local_products_path(local) %></td>
        <td><%= link_to 'Edit', edit_local_path(local) %></td>
        <td><%= link_to 'Destroy', local, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Local', new_local_path %>

app/views/locals/new.html.erb
<h1>New Local</h1>

<%= render 'form', local: @local %>

<%= link_to 'Back', locals_path %>

app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @local.name %>
</p>

<p>
  <strong>Razonsocial:</strong>
  <%= @local.razonsocial %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @local.rut %>
</p>

<%= link_to 'Edit', edit_local_path(@local) %> |
<%= link_to 'Back', locals_path %>